### PR TITLE
Send a message to the general discord channel on server startup

### PR DESCRIPTION
**Pull request by bloxgate**
Sends a notification to #general on server startup

Requested by @caelaislinn

### CODE REVIEW

**Comment by Maxattacker** [comment]
Have it so it will ping a "subscriber role" on server startup.

**Comment by bloxgate** [comment]
I'll need that role to be created on the server, and then ideally its snowflake ID.

**Comment by Maxattacker** [comment]
what do you mean its snowflake ID? I've made the role.

**Comment by bloxgate** [comment]
There should be a way to right click the role and hit the copy ID button. If you can't find it, I can just work around it and do it by name.

**Review by caelaislinn — APPROVED** [review]

**Comment by caelaislinn** [comment]
Would you like this merged now, or wait and put more features in?

**Comment by Maxattacker** [comment]
565786399983534081 heres the role ID

**Comment by bloxgate** [comment]
We should wait Cael. It seems like the consensus is we should make it either ping a role (which is being worked on at the moment), or have this just go to its own channel entirely.

**Review by BDpuffy420 — APPROVED** [review]

**Comment by BDpuffy420** [comment]
Progress ?

**Comment by bloxgate** [comment]
~~@Maxattacker server is now saying that that is a deleted role?~~ NVM

**Comment by bloxgate** [comment]
Alright, it pings a role when sending to the general channel now (assuming that that mention works right). Should be ready, I think?

**Pull request merged**
