### PR TITLE
First Contact fixes.

### PR DESCRIPTION
**Pull request by Flaksim**
*Clears up some map errors on exoresearch, removes radiation source.
*Adds a ODST security detail to exoresearch, whitelisted as regular ODST's.
--->Security shares spawnpoints with researchers, couldnt figure out how to create a new, separate spawn for them, only a minor issue.

### CODE REVIEW

**Review by bloxgate — COMMENTED** [review]
Normally Travis would tell us if this was ok, but that doesn't seem to be working at the moment (@BDpuffy420 pls fix)

Does this not require us to run the update globals script?

**Review by BDpuffy420 — DISMISSED** [review]

**Comment by BDpuffy420** [comment]
fixed

**Review by bloxgate — DISMISSED** [review]
Looks like there are 2 actual issues with the unsc_frigate now.

* It has an area with duplicate APCs.
* Multiple areas are defined that are not used

Both of those will need to be fixed

**Review by BDpuffy420 — CHANGES_REQUESTED** [review]
maps/unsc_frigate/unsc_frigate-4.dmm:31:error: undefined type: /obj/item/weapon/melee/combat_knife

**Review by BDpuffy420 — APPROVED** [review]

**Comment by X0-11** [comment]
#586

**Pull request closed without merging**
