### PR TITLE
Sangheili Secondary Armor Sprites

### PR DESCRIPTION
**Pull request by nameacow**
Adding multiple new sprites so that every class of Sangheili is unique and not just a re-color. Potential plan to add a secondary armor system akin to ODST's four 'classes' (without the different tiny perks each has).

also first PR so i could be doing this completely wrong!! we will find out!!

- [x] Major Sprite 
- [x] Spec-Ops Sprite 
- [x] Ultra Sprite 
- [x] Coding additions

:cl: nameacow01
rscadd: Multiple new secondary skins for Sangheili, all based off Reach armors. Ranger, Spec ops, Ultra.
/:cl: nameacow01

### CODE REVIEW

**Comment by nameacow** [comment]
i should probably stop testing github functions on a pr, huh

**Comment by nameacow** [comment]
All the coding additions and majority of sprites are complete. Hopefully I can get the Shipmaster sprite and some personal testing done by the end of the week.

**Comment by nameacow** [comment]
Everythings done, Just a pit of personal testing then putting up for review and merge, yipee.

**Comment by BDpuffy420** [comment]
Once your test are done I believe hitting ready for review will set it PR in motion!

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
