### PR TITLE
Deck one 

### PR DESCRIPTION
**Pull request by Kmc2000**
Mapped deck one and cael ale added

### CODE REVIEW

**Comment by bloxgate** [comment]
There is a merge conflict. Please redo the conflicting work, after rebasing onto the current alpha branch. And make sure to use the map merger.

**Comment by bloxgate** [comment]
Reopening since #131 should make this mergeable.

**Comment by Kmc2000** [comment]
Made a better one

**Comment by bloxgate** [comment]
This one is fine

**Comment by Kmc2000** [comment]
I'm bad


Also may or may not have added a caelcave and other maint fun things

**Pull request merged**
