### PR TITLE
Cassius Station Rework

### PR DESCRIPTION
**Pull request by Max-023**
The first deck has been heavily rearranged, with a emergency armory in case the Armory is too far off being added. MA5Bs and M6Ds made available with some ammunition for them located in the lockers north of the barracks and through a door. The medbay is tweaked to have a second surgery room, a storage room with some medical supplies located in crates, 4 IV drips (two for surgery, two for other), a blood bag crate, and a pill bottle box for the chem room. A second autosurgeon and body scanner have been added, as well, and now the anesthetics are able to be reached. The bridge is reworked and moved, now containing a scanning console, local comms console, global deck gun console, and navigate console. A nonfunctioning MAC firing computer and reloading terminal is present as well as a capture node in case further development is made on the prospect of base capture. A CO and XO office have been added, containing rank tabs for both branches for in round organization, as well as a spare barricade room in the XO office for bridge fortifying and the nuke room located off the CO office. A Crewman gear area has been added near the XO's office so that Marines wanting to be shipcrew can take on the uniforms. Additionally, a janitorial closet and kitchen have been added for qol, as well as a second staircase closer to the bridge, making the bridge and barracks two separate areas that are unable to be locked down at the same time with ease.

Deck two now has major restructuring, now with a better armory with 4 armor and 4 weapons vendors. An additional heavy armory has been attached. This should encourage the usage of the base over the Bertels as the main base of operations. Additionally, a very small ODST prep room has been set across the hall from the Marine armory and has one ODST vendor so ODSTs can gear up if the ship is away. An additional M41 and some rockets have been added on a rack just for some choice. The 3rd deck is now really spread out with many hallways going to each individual room. This is to slow down base rushing and allow for the defenders hold on to more ground. The training area has been moved to be farther out and a hangar with a single pelican has been added so Marines can head to the planetside and land directly at Crescent. The umbilicals have been moved and separated to create several points of ship boarding entry, as well.

This might not be 100% finished upon first playthrough, but further improvements can be made moving forward.

:cl: Max-023/Guprei/Stormtrooper
rscadd: Cassius_station_1
rscadd: Cassius_station_2
rscdel: Old Cassius_station_1
rscdel: Old Cassius_station_2
/:cl:

### CODE REVIEW

**Comment by X0-11** [comment]
please fill the description of the PR with all the changes made.
Also, travis is failing.

**Comment by Max-023** [comment]
Added a description. Hopefully that works for you.


I also have no idea what that means for Travis, but that sounds bad.

**Comment by X0-11** [comment]
Failing travis means the PR cannot be merged until you fix the issues it points out.

**Review by X0-11 — CHANGES_REQUESTED** [review]
The addition of more heavy weapons vendors and a loose rocket launcher is unwarranted. The bertels map should be modified to remove heavy weapons vendors to balance the numbers.

The loose rocket launcher + ammunition should be removed.

The extra pelican isn't needed in any way and unbalances the air-vehicle counts of the factions.

Non functional consoles should not be placed (MAC firing and reloading console). The capture node shouldn't be placed either due to potential issues. The deck gun console is unneeded too.

4 weapons and armour vendors seems a little too high. Cutting that down to 2 of each would be more reasonable.

Fleshing out the facilities available on the station is a good step to take.

Feedback is based on provided description of map.

**Comment by Max-023** [comment]
These are changes done with a new ship I am working on in mind. I am also working on a much smaller UNSC vessel that will have much less than what the Bertels has.


I also fail to see how a singular pelican throws off the balance considering that the hangar is farther out from the base like the training room and not easily accessed if the station was attacked. I can, alternatively, make the hangar large enough to have another dropship and allow the Covenant to bring their Spirit in through the hangar and land troops down there. I do want to keep the hangar as it would allow for moving stuff from the ship to the base and vice versa, as well as easy access to crescent.

**Comment by X0-11** [comment]
These changes stand alone unless the ship is PR'd alongside them.

The pelican is simply a numbers issue. It modifies the balance too much to be allowed.

This goes for the other issues including the vendors.

**Pull request closed without merging**
