### PR TITLE
Changes job roles

### PR DESCRIPTION
**Pull request by caelaislinn**
Mostly; trims a load of job roles from UNSC and Covenant. Jobs removed: 
- Prophet
- Honour guard
- Grunt major (merged with grunt minor)
- Kigyar major (identical to kigyar minor)
- Skirmisher Minor, Skirmisher Major
- ONI security squad leader and ONI research director
- Bertels IWO, Bertels crew

Other changes: 
- Marine leader and ODST officer gain access to Bertels armoury.
- Add Skirmisher Commando slot. 
- Rebrands URFC as SOE

:cl: Cael_Aislinn
tweak: Removes or merges many redundant job roles including Prophet, Honour Guard, Skirmisher majors and minors, Bertels IWO and crew.
tweak: Adds Skirmisher commando slot to Covenant.
tweak: Gives Bertels marine platoon leader and ODST leader access to Bertels armoury.
/:cl:

### CODE REVIEW

**Comment by daPotato** [comment]
> ONI research guards and research director

Theres something wrong with removing that, can't seem to put my ONI on it though.

**Review by BDpuffy420 — DISMISSED** [review]
What’s point if disabling RD/ONI guard then leaving base researchers. Might as full fully remove oni and VT9 because it’s useless. 9/10 times there not enough unsc to properly respond to VT9 when it does get attacked and removing the guards only makes it harder on the unsc but makes it more of a cake walk for covies. Highly disapprove of these changes

**Comment by BDpuffy420** [comment]
And secondly removing ship crew and IWO is god fucking awful I DO NOT WANT GREENTIDE HAVING ACCESS TO THE ARMORY PERIOD, doing this only to promote lowrp marines who know how to do everything John halo syndrome.

**Comment by CdrRiley** [comment]
im not for the hole pr chang really

**Comment by mcalexev** [comment]
I'm not really for the proposed job removal. I like having options, and I've only just made my return to the server to find all these awesome new things. ;_;

**Comment by Max-023** [comment]
Yeah, this ain't it chief.

**Comment by caelaislinn** [comment]
Re-added ONI security guard

**Comment by caelaislinn** [comment]
Role creep needs to be cut back, and I've been talking about this for a few weeks. Giving marine platoon leader and ODST officer access to the armoury has been requested by UNSC players for a while. 

I readded ONI security guards, but VT9 is still up to be shaken up. I'd like to cut it out and merge it with Geminus to save zlevels

**Comment by FooliusIV** [comment]
Why not just merge the Hospital Corpsman job into Ship Crew?

**Comment by CdrRiley** [comment]
no merging into ship crew may HC

**Comment by caelaislinn** [comment]
Lmao it's label tag with @BDpuffy420

**Review by bloxgate — APPROVED** [review]
Codewise this seems fine.

**Remove the html/changelogs/cael_*.yml before merging please**

**Pull request merged**
