### PR TITLE
More incendiary weapon fixes

### PR DESCRIPTION
**Pull request by caelaislinn**
Flame weapons should work properly now. 

:cl: Cael_Aislinn
experiment: Partially replaces ZAS fire with a simpler system that should make incendiary weapons (flamethrower, chem grenade, landmine) work properly. As it is partially integrated with ZAS, there may be some unusual behaviour in situations where simple fire and ZAS fire both appear. 
rscadd: NPCs can now ignite. 
rscadd: NPCs scream and run in fear when they are taking damage. 
/:cl:

Ready to merge

### CODE REVIEW

**Comment by X0-11** [comment]
do flames respect shields and armour?

**Comment by caelaislinn** [comment]
They should be doing that already, so that is unchanged

**Comment by X0-11** [comment]
How is the damage for when a mob is in the fire-spot vs just having the lingering fire effect? I assume flame weapons are going to be area denial, so the damage from the lingering effect should be pretty low.

**Comment by caelaislinn** [comment]
The damage per tick of being in the fire is 1 for napalm fires, but can go up to 6 for hellburn mixes. Being ignited appears to apply standard overheating damage which is 2, 4 or 8 per tick depending on the body temperature, which depends on the number of "fire stacks" gained from standing in the fire.

**Comment by caelaislinn** [comment]
#1120

**Comment by caelaislinn** [comment]
Ready to merge

**Pull request merged**
