### PR TITLE
Everything I Never Pushed

### PR DESCRIPTION
**Pull request by TalkingCactus**

### CODE REVIEW

**Comment by bloxgate** [comment]
Merge conflicts will need to be fixed.

**Comment by TalkingCactus** [comment]
I'm busy right now so I'll have to do it some other time, or someone can manually merge the map file if they want it sooner.

**Comment by caelaislinn** [comment]
I've made significant map updates to both levels of the innie base, the changes aren't mergeable. I'll have a look tonight.

**Comment by caelaislinn** [comment]
Can you itemise the changes you have made to the maps here? I'm going to manually merge with the changes I've made locally to the two innie base maps. The changes I have discovered so far are: 
- Overlaid an area, put in an APC + SMES for both levels
- Put in a messaging server + messaging mainframe for both levels
- Setup the port large (shuttle) airlock with what appears to be correct tags (I'm still testing it). I notice you used the new hangar vents I created specifically for these super large airlocks so well done. 
- Setup the starboard shuttle airlock with one incorrect tag (the inner blast doors are tagged "innie_lower_starboard" when they should be "innie_lower_starboard_inner", and you misnamed the controller (it's still called _Port_ Airlock Controller). 

My changes are fairly significant, so I was just going to copy paste the finished shuttle airlocks over.

**Comment by BDpuffy420** [comment]
Progress on this Cael?

**Comment by caelaislinn** [comment]
I've begun moving over the map changes but it will take a little time to fix and test the airlocks. I can merge the code and sprite changes quite quickly once everything else is done. My innie base PR is on hold until I can get in a fix for the shuttles which isn't looking like a simple issue.

**Pull request closed without merging**
