### PR TITLE
General Geminus and more QOL

### PR DESCRIPTION
**Pull request by BDpuffy420**
*adds more life to the city
*Revert Geminus MAC setup nerf
*Updates URF base
*Updates Geminus mining
*Updates Welcome/ending ogg
*Adds more Halo theme to movie credits

### CODE REVIEW

**Comment by caelaislinn** [comment]
You didn't commit any changes for the end round credits or audio

**Comment by BDpuffy420** [comment]
Still working on it, about to pr it

**Comment by caelaislinn** [comment]
changelog

**Review by caelaislinn — DISMISSED** [review]
changelog

**Review by caelaislinn — APPROVED** [review]

**Comment by BDpuffy420** [comment]
Don't merge just yet got some last minute lines to add, they were too good not to add

**Comment by BDpuffy420** [comment]
Well Travis is being AIDS again

**Comment by BDpuffy420** [comment]
PR passing

**Pull request merged**
