### PR TITLE
General QoL

### PR DESCRIPTION
**Pull request by BDpuffy420**
:cl: BDpuffy420
tweak: Updated kig-yar NPC ship sprite and added SDV to the NPC pool
rscdel: Remove some lights from Geminus to help with Travis test
rscadd: added the m45 TS and fixed the m90 sprite
rscadd: Added SoE to Rev mode
rscadd: New shipnames
bugfix: M7/M7s inhand should be fixed
bugfix: Fixed the fuelrod sprite
bugfix: Fixed type-51 in-hand
bugfix: ONI has UNSC faction tag
bugfix: x52 shouldn't spawn in reclamtion now
maptweak: fix blocked ladders on Geminus
spellcheck: fixed the text error of x-25 to x-52
/:cl:

### CODE REVIEW

**Comment by BDpuffy420** [comment]
Geminus having a stoke

**Comment by caelaislinn** [comment]
Self merge without an approving dev and making significant changes which weren't discussed beforehand

**Comment by caelaislinn** [comment]
:-1:

**Comment by BDpuffy420** [comment]
Ain't No Laws When You're Drinkin' Claws. 🤷🏾‍♂️

**Comment by BDpuffy420** [comment]
Ain't No Laws When You're Drinkin' Claws. 🤷🏾‍♂️

**Pull request merged**
