### PR TITLE
Fix CMO uniform

### PR DESCRIPTION
**Pull request by bloxgate**
Was using the wrong icon file.

### CODE REVIEW

**Comment by caelaislinn** [comment]
Can you fix the pixel offset issue with the captain's jumpsuit as well? /obj/item/clothing/under/unsc/captain

**Comment by bloxgate** [comment]
I can, where do you want me to move the pixel to? There's 3 or so spots that look right.

**Comment by bloxgate** [comment]
Can't fix captain's uniform, it's 1px too small. Get the spriters to fix

**Comment by caelaislinn** [comment]
Looks good. Sorry for not going over this earlier. I've been going over the other items, can you put up fixes for the marine helmet as well? I noticed there are also 2 sets of marine gear, the current set and newer ones done by kmc2000 which I think are nicer. We might need to get comparisons of the 2 done then a decision made. 

Also while you're doing fixes the MA5B has a broken sprite and the railgun doesn't appear to fire correctly.

**Pull request merged**
