### PR TITLE
new ODST armor

### PR DESCRIPTION
**Pull request by ZAB909**
sproites by riot officer #0772

look in US embassy for sprite pics.

:cl: Zab1019
rscadd: new odst onmobs and objs
rscdel: del old odst onmobs and objs
/:cl:

### CODE REVIEW

**Comment by X0-11** [comment]
Example images?

**Comment by CapCamIII** [comment]
@ZAB909 The DMI you were given is not my sprites, FYI.

**Comment by ZAB909** [comment]
Read desc. They're in us channel

**Comment by ZAB909** [comment]
It isn't in progress. It's done

**Comment by BDpuffy420** [comment]
Those aren't the right sprites it seem

**Pull request closed without merging**
