### PR TITLE
[READY TO MERGE] Cargo Overhaul

### PR DESCRIPTION
**Pull request by Aroliacue**
:cl: Aroliacue
tweak: Major cargo overhaul. Prices reduced and more items added to encourage purchases of equipment that can then be deployed onto a planet via pods found in cargo rooms.
rscadd: Added a new 'Requisitions' channel to UNSC and Covenant to organize requisition drops.
/:cl:

### CODE REVIEW

**Comment by Aroliacue** [comment]
Feedback or additions encouraged while I work on this

**Comment by Aroliacue** [comment]
UNSC basically finished, will work on Covenant tommorow and will take a look at the unique Innie supply code (if I can comprehend it)

**Comment by Aroliacue** [comment]
Covenant finished, going to look into adding some extra categories and some more spicy stuff

**Comment by Aroliacue** [comment]
Added a new misc category with covvie deployable items, lights and pinpointers for both sides (essential pinpointers cost more for UNSC)

**Comment by Aroliacue** [comment]
Just need to test and make sure Innie cargo isn't broken by any changes, then will be ready to merge.

**Comment by Aroliacue** [comment]
Ready for review and merge.

**Review by X0-11 — APPROVED** [review]

**Pull request merged**
