### PR TITLE
Removes the needed access to use the medical vendors in KS7's hospital

### PR DESCRIPTION
**Pull request by enkidienne**
:cl: Enkidienne
maptweak: Medical vendors are now usable by colonist due to removing the needed access.
maptweak: Changed the Vendors's name to fit the colonial setting. 
/:cl:

### CODE REVIEW

**Comment by X0-11** [comment]
Aren't these set to the doctor job's access?

**Comment by enkidienne** [comment]
maybe, but its not really usefull if a single very unused role can use them

**Comment by X0-11** [comment]
But the job is why the vendors exist in the first place. There's at least one drug-den on the map that you can use to synthesise your own.

**Comment by enkidienne** [comment]
yes but are the colonists supposed to brew all their medicine if a single role isnt there? that dosnt seem very viable?

**Comment by X0-11** [comment]
Colonists are meant to spawn into jobs: It's a mainly RP role, and so you're expected to stick to that. I'd allow the addition of loose medical supplies to the hospital lobby like burn and brute packs.

**Comment by enkidienne** [comment]
i agree, but those basic meds are simply no enough for most injuries, and too many times around there is no hospital worker to actually vend the useful stuff. All that leave the colonists in a weird spot where they cant get meds from normal ways most of the time.

**Comment by X0-11** [comment]
Hmm. Put some basic meds into the hospital lobby and also feel free to integrate a secret small hospital into one of the rock-walls.

**Comment by enkidienne** [comment]
> Hmm. Put some basic meds into the hospital lobby and also feel free to integrate a secret small hospital into one of the rock-walls.
 ok

**Pull request closed without merging**
