### PR TITLE
URf updates Some Items and Random Clothing

### PR DESCRIPTION
**Pull request by lngredients**
So I wanted to add random clothing to the URF base for a while now. I also hated the fact that all the cargo crates in the storage rooms don't have anything in them so I am putting this PR forwards in an attempt to actually make them useful.

Added in random clothes sets in Innibase3 Laundry room and Eastern Storage.

Added in five voice analysers into Engineering storage in Inniebase3 so innies.

Added in a small assortment of old guns with a bit of ammo into the ammo crates Inniebase3 north storage. Added in a few sets of armor vests. 

Added in two random medkit spawners and four random eyewear spawners. to Inniebase3 north storage.

Added in randomised misc items to Eastern and Northern Storage in Inniebase2. Should help with blending in with civies if they want to go incognito. Added in a emergency rations freezer as well.

Added in a few old style guns to the weapons crates in Northern Storage Inniebase2.

Added in some merc armor and helmets into northern Storage Inniebase2.

Added in a secure briefcase with money inside of it in the hidden office in eastern maint in Inniebase2. Also added in a case of cigars.

Added barricades over the grills on Inniebase1 to make it more difficult to enter through vents.

### CODE REVIEW

**Comment by lngredients** [comment]
Damnit... Why do you conflict!?

**Comment by lngredients** [comment]
This should be good to go if the CI passes everything but the map image.

**Review by caelaislinn — APPROVED** [review]

**Comment by lngredients** [comment]
What is this!?

**Comment by lngredients** [comment]
Merge it!

**Pull request merged**
