### PR TITLE
Various changes to signal-transmission, Comms and otherwise.

### PR DESCRIPTION
**Pull request by X0-11**
Adds overmap-range handling to signal transmissions, using certain comms equipment as relays for the signal to create a bounce-path across the overmap.
Overmap range-handling requires a valid node on the overmap object.
Ranges are based on the transmitting object of the signal, allowing for one-way communication.
Adds comms-jammers, with a variable range, chance and amount of compression induced into the signal.

### CODE REVIEW

**Comment by bloxgate** [comment]
So I could be completely misreading this, but is the range falloff linear?

**Comment by X0-11** [comment]
Range falloff isn't currently applied due to the requirement of a reciever on each z (or connected zs with long range link enabled)

**Review by DoctorOctopusTheOctopi — APPROVED** [review]
Looks good from my point of view. Minimal map changes, nothing looks sloppy code-wise, code looks like it'll work and I'm sure XO has playtested it.

**Review by BDpuffy420 — APPROVED** [review]

**Comment by caelaislinn** [comment]
I was hoping to review this but it would have been a big job. Live testing is more fun anyway :)

**Pull request merged**
