### PR TITLE
Voteable mapswitcher

### PR DESCRIPTION
**Pull request by caelaislinn**
To use: Run generate_switchable_maps.sh each time you do a code update or the alternate DMBs will be on an outdated codebase. This shell script will only take 1-2 minutes per map and can be run while the server is active. 

Switching a map can be done ingame with either Admin-switch-maps verb (requires R_SERVER) or a vote (requires R_ADMIN unless config.allow_map_switching == 1)

### CODE REVIEW

**Comment by X0-11** [comment]
Has this been tested on, at least, First Contact?

**Comment by caelaislinn** [comment]
Yes but I'll do another round of testing now. It works by compiling and switching all the separate DMBs so as long as the different map modes are functional there's not much that can go wrong

**Comment by X0-11** [comment]
When working with fragments of the Travis-God one can not be too careful.

Good to see this actually appearing after much talk about it though.

**Comment by caelaislinn** [comment]
I avoided it for a long time. It proved to be both more painful and faster to do than expected. Hostchat actually recommended python or possibly perl instead of bash but I wanted to learn bash for a long time

**Comment by caelaislinn** [comment]
I went through and tested all the maps again. There are icon caching runtimes with some of the maps. I'm pretty sure it's unrelated to the mapswitcher. The issues screw up something in the RSC and most of the icons are blank (critical bug). Maps affected are: 
- desert_outpost
- crashsite_zeta
- slayer

Maps working fine are: 
- Geminus city
- Insurrection
- ccs_battlecruiser
- doisac
- first_contact

Gamemode votes aren't callable by players yet, so this can still go live while we try to fix those rsc issues.

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
