### PR TITLE
Midway Medical Ship Addition

### PR DESCRIPTION
**Pull request by lngredients**
New Civilian Medical Ship (Will need to be looked over to make sure I didn't miss anything)

New Brand of Cigs called CMO Smokes

New Floorsign Icon for medbay locations

### CODE REVIEW

**Comment by lngredients** [comment]
You can mostly ignore this PR, I am mostly just testing out how to make a ship, I'll work on it on the side until it is merge-able, or delete it entirely if I can't get it. Unless someone is feeling gracious enough to give me some pointers about what I am doing wrong.

**Comment by caelaislinn** [comment]
Looks like Travis is failing because you haven't placed /area/om_ships/Midway on the map.

**Comment by lngredients** [comment]
I feel like I did, I used it to make the ship with, so I'm not sure why it's saying it's not there.

**Comment by bloxgate** [comment]
Your most recent change to the map includes merge conflict markers. You seem to have done something wrong with resolving the conflict.

**Pull request closed without merging**
