### PR TITLE
fixed up security

### PR DESCRIPTION
**Pull request by F-OS**
i added a interrogation room, evidence storage with tons of room, firelocks, wired in some apc's, made a warden's office, firing range, fixed the id's on cells, and some general tweaks.

EDIT:fixed dyslexia 
unsc_cruiser-1 dmm 0

### CODE REVIEW

**Comment by bloxgate** [comment]
@Kmc2000 does this mess with any of your stuff?

**Comment by F-OS** [comment]
kmc got to this before me. so on to deck 2.

**Comment by BDpuffy420** [comment]
Yeah but he hasn't messed with his map bit in ages so I might merge.

**Comment by bloxgate** [comment]
Yeah, his stuff has a merge conflict too, so we might just use yours.

**Comment by F-OS** [comment]
thanks.

**Pull request merged**
