### PR TITLE
HA -> Bertels Replace

### PR DESCRIPTION
**Pull request by X0-11**
Replaces the HA with the Bertels, pending a new UNSC ship. When a new UNSC ship arrives, the Bertels will be handed over to the URF.

Also buffs the Thorn by giving it a set of MAC cannons.

### CODE REVIEW

**Comment by BDpuffy420** [comment]
If there no IWO role I’m not merging this. [paperwork intensifies]

**Comment by BDpuffy420** [comment]
If there no IWO role I’m not merging this. [paperwork intensifies]

**Comment by BDpuffy420** [comment]
If there no IWO role I’m not merging this. [paperwork intensifies]

**Comment by X0-11** [comment]
Ask and ye shall recieve. IWO job added, coinciding with the removal of a large amount of heavy weapons ammunition from ODST heavy armoury and relocking of ODST heavy armoury.

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
