### PR TITLE
Ammobox invisibility fix, shotgun ammobox quickloader.

### PR DESCRIPTION
**Pull request by X0-11**
Fixes ammobox invisibility.
Adds an item used by shotguns to quickly load shells.

### CODE REVIEW

**Comment by caelaislinn** [comment]
I forgot we didn't port over the icons I made for them. They'll be stashed away in the 0.2 branch but they were just quick resprite jobs that looked half decent. I'll dig around and pull them out when I get a chance

**Comment by X0-11** [comment]
Sprites for ammo box item obtained, other storage-system based boxes of ammo use the default box sprite. Should be ready for merge, barring any review changes.

**Comment by BDpuffy420** [comment]
LGTM

**Review by BDpuffy420 — APPROVED** [review]

**Comment by BDpuffy420** [comment]
baystation12.dme issue

**Review by BDpuffy420 — CHANGES_REQUESTED** [review]
baystation12.dme

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
