### PR TITLE
Minor map fixes, not changelog worthy.

### PR DESCRIPTION
**Pull request by Flaksim**
*Added a missing shutter button and ID. 
*Renamed a door properly.
*Added a missing wall tile.

Closes #704

### CODE REVIEW

**Comment by bloxgate** [comment]
Did you add another level to this? That will break things. We are beyond the max limit for connected Z-levels in the current code, and right at the limit that #704 would set.

**Comment by Flaksim** [comment]
It wont break your fix, I also included a load order change that makes the linked levels load in first, so they arent in danger of being over the 25 level limit. It'll work for the time being, but imo we need a different system, and also use different modes for different mapsets instead of the humongous all in one mode we have right now.

**Comment by bloxgate** [comment]
Well, in that case 🎉

**Comment by Flaksim** [comment]
This can be merged pending review.

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
