### PR TITLE
Misc Covenant work

### PR DESCRIPTION
**Pull request by caelaislinn**
Highlights:
- New spartan mob and armour sprites
- Various code cleanups
- Mjolnir and Sangheili Ranger suits can now hold oxygen tanks
- Some tweakfixes to the new thrusters
- Grunts now have natural armour on their hands as well as feet
- Covenant chemdispenser sprite by Spider Psycho
- New faction whitelist system. Treat it the same as a species whitelist, except instead of species put the faction name ("Covenant","UNSC","Insurrection") (admins ignore this whitelist when checking job availability)
- Adds an admin verb to reload whitelists while the server is running
- Adds placeholder slipspace engine for mapping

### CODE REVIEW

**Comment by caelaislinn** [comment]
Still testing some stuff to do with thrusters

**Comment by caelaislinn** [comment]
Ready to merge

**Comment by caelaislinn** [comment]
Travis fail is the exoplanet simple_mob

**Comment by caelaislinn** [comment]
#755 #754 #688

**Review by Flaksim — APPROVED** [review]
Looks like solid work, the new engines and work on specials is the highlight here.

**Pull request merged**
