### PR TITLE
Autosurgeon fixes

### PR DESCRIPTION
**Pull request by caelaislinn**
:cl: Cael_Aislinn
bugfix: Rewrote autosurgeons for embedded object and bone fixing. Hopefully it is working now
bugfix: Geminus surface no longer uses dynamic lighting. This has resulted in a few minor lighting artifacts for a significant optimisation. 
/:cl:

### CODE REVIEW

**Comment by caelaislinn** [comment]
#1736

**Comment by BDpuffy420** [comment]
Local Travis angry

**Comment by caelaislinn** [comment]
Yeah this fix isnt even working anyway

**Comment by BDpuffy420** [comment]
Thank fuck Travis is pleased

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
