### PR TITLE
Far-Isle mapsize reduction.

### PR DESCRIPTION
**Pull request by X0-11**
Cuts off the caves from z-level 2 and 3, cuts down the amount of space taken up by the ocean. Removes 3 random space tiles in the middle of nowhere. (might've been the cause of all the lag)

### CODE REVIEW

**Comment by X0-11** [comment]
Changes tested, Looks like it improves the lag issue.

**Comment by BDpuffy420** [comment]
So the random space tiles were the cause?

**Comment by X0-11** [comment]
Random space tiles and the sheer size of the map
I've lopped off most of the caves and have shortened the size of the sea area

**Comment by BDpuffy420** [comment]
Neat, I feel it was a mixture that and the server box itself. but cool LTGM

**Pull request merged**
