### PR TITLE
Adds separate jobs for the Deliverance

### PR DESCRIPTION
**Pull request by erty80s**
-Added Medic Ship Crew spawn and job to the Deliverance

-Added Medic Ship Captain spawn and job to the Deliverance

### CODE REVIEW

**Comment by caelaislinn** [comment]
Looks fine. Can you add a changelog entry?

**Comment by erty80s** [comment]
Sure I'll do it tomorrow though when I get back from work

**Comment by BDpuffy420** [comment]
conflicting flies

**Comment by erty80s** [comment]
Is it a big issue? I'll try to fix it without breaking my local copy

**Pull request closed without merging**
