### PR TITLE
fixes commando spawns?

### PR DESCRIPTION
**Pull request by X0-11**
title

### CODE REVIEW

**Comment by caelaislinn** [comment]
This is a bandaid fix. It should never have been a problem because there should never have been unique spawn type definitions for jobs. I have a strong preference that the issue with URFC spawns is "fixed" by removing the custom spawn type definitions

**Comment by X0-11** [comment]
They could easily be changed to spawn on the faction's base, however, I was asked by the Insurrectionist faction leader to keep their spawns on the Avarice.

**Comment by caelaislinn** [comment]
I think alternate spawn types for jobs should be functionally similar and not offer a large strategic advantage (small one = probably fine). Instead, a different job should be given with the alternate spawn method. 

Are you interested in doing a cleanup to remove the custom spawn definitions? I'm ready to jump in and do it now

**Comment by X0-11** [comment]
Go ahead and do so, most of them aren't being used and the files are unincluded.

**Pull request closed without merging**
