### PR TITLE
Added Civilian Freighter Map

### PR DESCRIPTION
**Pull request by CaelumPR**
Added a Lore-Friendly Freighter map, complete with a propulsion pod for the 1 man crew!

### CODE REVIEW

**Comment by DoctorOctopusTheOctopi** [comment]
I'll be reviewing this once it gets completed then throw it over to @Desolane

**Comment by DoctorOctopusTheOctopi** [comment]
Hiya. I've come to give my thoughts on the map. Most of it was good there was just a few rookie mistakes that can be easily ironed out with a bit of advice.

For starters I think its aesthetically pleasing to not using curtains on [corners,](https://gyazo.com/7af4c621a5cf4381e6a3b1bf4914adc6) instead using a solid wall, barricade, barrier or something of the sort This is just because of the way curtains are sprited, it isn't required its just a personal opinion. and remember that the base item is always the first item in the stack so in the case of random object, that is just the base item and will not do anything on its own, using the dropdown menu will expose other randomized items.

Your airlocks need airlock sensors, scrubbers, vents and endcaps. The APC is also facing the wrong direction. I'll also let you set up fuel supply and engines for the ship to be overmap capable. I'll have the areas defined in a .dm will paste them over in your local fork should you want.

I think its really great how you stuck to the lore-friendly version and crafted a cargo hauler to reflect that, everything down to the airless tiles. Should you wish to make the entire thing lack gravity I can and will set the gravity of your specific area to zero.

Overall this is a great first map and it will make an excellent addition to our NPC Ship system as a civillian vessel. We are always looking for other additional items to be mapped that are relatively for [beginners](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues?q=is%3Aissue+is%3Aopen+label%3A%22New+Contributor+Friendly%22). and should you require any assistance you can always send a help request to our #mapperbus channel in discord.

I encourage you to apply for the position of mapper should you wish to pursue this avenue within the server development team, if you do not want to pursue a mapper we are always looking for talented spriters and coders as-well. I will be adding your map to my PR #528 and setting it up for overmap. I will be using it for the NPC Ship System. I'll tag @Desolane Should he wish to comment anything. Good luck in all your future mapping endeavors.  👍 🐙

**Comment by X0-11** [comment]
#528 Implmented there.

**Comment by DoctorOctopusTheOctopi** [comment]
Thank you for the contribution again, we can speak more on discord if you want to pursue the position of Mapper with us.

**Pull request closed without merging**
