### PR TITLE
cool spartan stuff

### PR DESCRIPTION
**Pull request by CapCamIII**
going over changes in CL 1 by 1

1. the gun's sprite looked cool and I thought it would be neat, i also made the sprite a bit cooler IMO IMO IMO; regarding its stats, it is a side-grade to the MA5 with a fast but inaccurate 5 rnd burst, and a very accurate but only 3 rnd burst. Also letting it use MA3, MA5, and MA37 mags means it can be used easily by both URF(MA3 and MA37; as well as stealing MA5 mags from UNSC) as well as UNSC having their high-cap MA5 mags.

<details><summary>pic</summary>
<p>

image

</p>
</details> 

2. QOL stuff for if an agent or researcher gets orioned, or a spartan/agent somehow loses their interface(or gets admin spawned)
3. i took the sprite and general idea from the orion gun so they get it, and spartans getting it too would be cool i think
4. breaching charges shouldnt be that expensive IMO. and neural laces are basically only for post-orioning and if someone somehow loses theirs(like an aheal), and I don't think that should be penalized
5. QOL as orioning someone takes out their interface
6. I think spartans getting translation capabilities would increase their self sufficency by a good bit, and if CO/oni agent gets it so should they
7. bug
8. bug

i made this in 2 hours so if it works im a beast

:cl: riot
rscadd: Half adds a new gun based on the orion M98 carbine, the XM98, MA5B with the ability to use MA3 MA5 and MA37 mags
rscadd: Adds an ONI and spartan neural interface injector for admin-spawn
tweak: Gives the XM98 to spartans and URF Orions
tweak: Orion transform crate now contains a neural interface injector, as the orionification process removes your original
tweak: Spartans now get a sanghelli language phamplet
bugfix: Orions now have human names by default
bugfix: Spartans should be able to use ONI Cargo now
/:cl:

### CODE REVIEW

**Comment by X0-11** [comment]
The new gun shouldn't be some sort of better-than-both variants; it should have some downside to it's use, and especially shouldn't have a scope

The various access laces shouldn't be added to cargo, as anything further than standard access is intended for admin spawning.

The costs for most items are set higher than if they were the only way to get that item, because you can get them from vendors for free. I don't think halving the cost should be done. Either way, these sort of changes need to be mirrored to the urf and covenant cost lists too.

**Comment by CapCamIII** [comment]
@X0-11 Changed rifle to a 3rnd accurate/fast 5rnd inaccurate/fast burst, so its kinda a BR with less damage but the ability to do bigger(but less accurate) bursts; as well as when using the MA5; larger magazines

killed the other two things(still added oni/spartan neural lace for adminspawn tho) :D

**Comment by X0-11** [comment]
Alright, I'm fine with seeing where that goes. Just duplicate the  breaching charge and c12 changes to the other faction's armories and this looks good.

**Comment by CapCamIII** [comment]
By that I meant I removed the charge changes, I can re-add them to all if you would like though.

**Comment by X0-11** [comment]
My bad, they were still appearing on my  readout at the time.

**Review by X0-11 — APPROVED** [review]

**Pull request merged**
