### PR TITLE
Doors force open from 0.5 to 5 seconds and nuclear payload fix

### PR DESCRIPTION
**Pull request by Terror4000rus**
You can hack any unbolted (at practic - any) airlocks and use them in boarding or breaching in hostile instalation. Alright, it sounds legit, but not in 0.5 seconds.

### CODE REVIEW

**Comment by Terror4000rus** [comment]
A-and also a fix: "Fixing a bug when covenant can arm human bomb and vice verse."
Sorry for not creating another branch and PR for it -.-

**Comment by BDpuffy420** [comment]
I closed this by mistake, but this still needs a changelog

**Comment by BDpuffy420** [comment]
merge conflicts now

**Comment by Terror4000rus** [comment]
Someone already did it (in takes 5 seconds now), nevermind.

**Pull request closed without merging**
