### PR TITLE
Fixes Job Access Issues (Hopefully)

### PR DESCRIPTION
**Pull request by X0-11**
First attempt at using BYOND's DM code, hopefully I replaced the right things.

Changes access requirements on lockers and vending machines to access used in unsc_ship.

### CODE REVIEW

**Comment by bloxgate** [comment]
LGTM, I'm going to request that Cael takes a look at this too though.

**Comment by caelaislinn** [comment]
These are the ones on the map: 
/obj/structure/closet/secure_closet/freezer/kitchen
/obj/structure/closet/secure_closet/medical1
/obj/structure/closet/secure_closet/medical2
/obj/structure/closet/secure_closet/medical3
/obj/structure/closet/secure_closet/chemical
/obj/structure/closet/secure_closet/medical_wall

These ones aren't on the map, but may be useful: 
/obj/structure/closet/secure_closet/injection
/obj/structure/closet/secure_closet/brig
 /obj/structure/closet/secure_closet/wall

SS13 job specific lockers should not be mapped in. There are job specific lockers for the UNSC jobs already. The gun lockers in the armoury and the APCs also need their access reset. Stuff like boozemat and courtroom lockers are never going to be placed on a UNSC warship :P

Light fingers coding practice applies here, the less we touch that we don't have to and the less breaks.

**Review by caelaislinn — COMMENTED** [review]
---

**Review by caelaislinn — CHANGES_REQUESTED** [review]
- Remove changes to SS13 job lockers (including boozeomat, courtroom etc)
- Add fix to APC access
- Add fix to armoury gun locker access

**Comment by X0-11** [comment]
APCs already have tech access, lockers in the armoury seem to be set correctly.

Sorry for the commit spam, online editor.

**Comment by caelaislinn** [comment]
There's a couple of crates in there that I don't think we'll use but it's basically harmless. Squash merging

**Review by caelaislinn — APPROVED** [review]

**Comment by bloxgate** [comment]
Just got a report that the CMO can't open any lockers in medical even with this merged.

**Pull request merged**
