### PR TITLE
Huragok implement

### PR DESCRIPTION
**Pull request by X0-11**
:cl: XO-11
rscadd: Implements Huragoks, with a fixed autoinjector, over-time self heal and two job slots onboard the covenant ship.
tweak: Energy proj pen lower
/:cl:

### CODE REVIEW

**Review by BDpuffy420 — COMMENTED** [review]
I see you removed Npc drones and hunter from covenant species list why?

**Comment by X0-11** [comment]
Npc drones are unused and mgalekgolo was in there twice

**Comment by BDpuffy420** [comment]
> Npc drones are unused and mgalekgolo was in there twice

Ah okay for the hunters but um npcs are still used for events and maybe more useful when playable drones are added for fodder for them

**Comment by X0-11** [comment]
I'm sure they can be readded when they also use the right typepath and not "done"

**Comment by BDpuffy420** [comment]
Fair point!

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
