### PR TITLE
Add build status indicator from travis-ci

### PR DESCRIPTION
**Pull request by bloxgate**

### CODE REVIEW

**Comment by caelaislinn** [comment]
Currently shows build: unknown. Is that right?

**Comment by bloxgate** [comment]
It shows as passing for me.

**Comment by caelaislinn** [comment]
Ah ok. How do you use it? :P

**Comment by bloxgate** [comment]
The image is linked to the Travis API so every time we push commits to the alpha branch it will update and let people know whether or not the current copy of the source code compiles or not. Ideally we'd have a separate one for each branch, though I'm just putting it somewhere where people will see it for now.

**Comment by caelaislinn** [comment]
Ah ok that's good then

**Pull request merged**
