### PR TITLE
UNSC Frigate Map - Now with propulsion!

### PR DESCRIPTION
**Pull request by X0-11**
Ports over the UNSC frigate map, with overmap propulsion and relevant comms devices, jobs and outfits.

Still devoid of elevators due to the mapping changes that would need to be made to incorporate them.

DNM : Want to integrate a gamemode or overmap sector to use alongside this.

### CODE REVIEW

**Comment by BDpuffy420** [comment]
APCs and hud icons

**Comment by bloxgate** [comment]
Once travis is happy I'll review, but it may have to wait for finals week to end.

**Comment by BDpuffy420** [comment]
I'd highly recommend  integrating insurrection, get back in touch with our roots.

**Comment by BDpuffy420** [comment]
Travis is still tripping

**Pull request merged**
