### PR TITLE
Added different spawn() delay code for grenade primers. (PR Ver.2 Elec. Boogalo)

### LINKED ISSUE #1437: Fragmentation Grenade Time
I believe we should reduce the time it takes of a primed frag grenade to go off from 5 seconds to 3 second.
Leaving targets enough time to run away but not too much time.
Any arguments?

### LINKED ISSUE #2351: Grenades do not have a prime timer that is accurate.
#### Description of issue

Grenade timers do not accurately represent the timer the grenade is acting on and are tied to server tick instead of actual time. This causes a 5-second grenade primer to experience time dilation due to the server not always running at 1 to 1 real-time in ticks and allows it to go longer than 5 seconds.

Related to #1437 

#### Difference between expected and actual behavior

The grenade has a 5-second primer but takes longer to explode.

#### Steps to reproduce 

Use a grenade.

Realize it takes longer than the primer says it does.

Cry.

#### Specific information for locating

All throwable primed grenades.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: ac715cdab770bce60ce2b13340ec152e14cb479f - alpha - 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

### PR DESCRIPTION
**Pull request by TheGandalf85**
Fixes #2351 and potentially fixes #1437

Added the delay for closer real-time emulation on grenade primers. This will cause more hands to roll if cooked compared to before, but the primers will lag with the server if each tick is experiencing 150% use or more, to prevent hands from rolling too hard.

**Note that this PR isn't heavily tested and needs to be done in the situation that warrants it. I'll do my best to test it locally and comment further on it. I suggest not accepting the PR yet until it's confirmed tested properly by either me or someone else.**

:cl: GameMaster85
rscadd: Made grenade timers follow realtime more closely instead of server time. Hands will roll.
/:cl:

### CODE REVIEW

**Comment by X0-11** [comment]
Changelogs are done in the PR rather than the file itself, otherwise, looks good. I saw your explanation in discord.

**Review by caelaislinn — DISMISSED** [review]
The changelog entry in your PR desc needs to be fixed

**Comment by TheGandalf85** [comment]
Changelog entry changed. Dunno how that happened. And thanks for the tip X0-11.

**Review by TheGandalf85 — COMMENTED** [review]
PR Desc changed.

**Review by X0-11 — APPROVED** [review]

**Pull request merged**
