### PR TITLE
Orion fixes

### PR DESCRIPTION
**Pull request by lngredients**
- tweak: "Fixed Orion Species Path so they can now wear their armor properly."
  - tweak: "Deleted three spare undersuits in orion closets as they were redundant."
  - tweak: "Changed the name of the Colossus Case to help it blend in better while holding it."
  - tweak: "Removed custom attack code for Orions."

### CODE REVIEW

**Comment by lngredients** [comment]
Closed the Old PR, opened up a fresh new one where these are the only changes I've made.

**Comment by lngredients** [comment]
So, if this happens to pass the CI, I'd appreciate another fresh review, I'll keep an eye on it as well to see what is wrong if anything.

**Review by Flaksim — COMMENTED** [review]
This looks good, not seeing any overtly bad changes.

**Review by Flaksim — APPROVED** [review]
Approved.

**Pull request merged**
