### PR TITLE
replaces the SOE vendors with some useless shit

### PR DESCRIPTION
**Pull request by enkidienne**
Replaces the SOE vendors on the ODP with a prop and a costume vendor. Was asked to do this by some admins due to abuse.

consider it done

### CODE REVIEW

**Comment by Stingray540** [comment]
It's worth noting that as an admin - we have no final say in the balances, so the admin who "told" you to do this was probably in the wrong.

I see no problem with having a small vendor filled with very limited weapons being there.

**Comment by enkidienne** [comment]
> It's worth noting that as an admin - we have no final say in the balances, so the admin who "told" you to do this was probably in the wrong.
> 
> I see no problem with having a small vendor filled with very limited weapons being there.

its 2 full SOE vendors. They have old unbalanced weapons that should not be in use anymore without a good round of balance

**Comment by YourPalHolidays** [comment]
Well this post was spurred on by a discussion I brought up between me and another admin, besides it has to be reviewed and accepted anyway and in that time there can be discussion on whether or not it should be removed or not.

My opinion is that, since SOE gear has always been whitelisted why should their equipment vendors be on the ODP, they serve no purpose other than meta because they contain outdated and un-balanced weaponry.

This all comes down to, is it whitelisted equipment or not? If so, then why is it on the UNSC ODP at all and can be easily accessed by so many, I've seen ODSTs and marines both utilized SOE gear, even down to their armor. If it isn't whitelisted anymore then SOE weapons and the vendor should still be removed and balanced and replaced later and to add that, why do they need SOE armor vendors?

**Comment by Stingray540** [comment]
To add on some other discussion that has been going around regarding this:

-Whitelisted or not should not be the argument as right now it's on the ODP and the marines have access. Therefore, it isn't actually "whitelisted" gear. If a grunt has access/is able to use an LMG is that really a "whitelisted" weapon?

-The main focus should be on the actual balancing of the gear inside. If it's overpowered and now being abused too much? Remove. But that's for XO to decide.

**Comment by enkidienne** [comment]
XO said to leave em here

**Pull request closed without merging**
