### PR TITLE
Dual Wielding, Two-hand requirement

### PR DESCRIPTION
**Pull request by X0-11**
Addition of a proc that can be added to a mob's verb list via add_verb that allows a person to hold two weapons and fire them at the same time.

Adds a value to stop players firing weapons if they don't have a free inactive hand.

### CODE REVIEW

**Comment by BDpuffy420** [comment]
#339

**Comment by X0-11** [comment]
Any additions to the dual_wield_allowed list in dual_wielding.dm will be useful, I probably overlooked a few weapons.

**Comment by caelaislinn** [comment]
This is... very clever. Have you looked into making the rifles 2 handed?

**Comment by X0-11** [comment]
Two handed: as in needs 2 hands to use, or 2 handed as in dual wieldable? If the former: They should have the var set to -1. If the latter, it's just a simple change to the DUAL_WIELDABLE_UNSC list define.

**Comment by X0-11** [comment]
Just a note too: This'll have to be manually added via add_verb to allow dual wielding; It's not currently in any species' inherent_verbs list.

**Comment by BDpuffy420** [comment]
code/modules/halo/icons/Weapon_Inhands_right.dmi

**Comment by X0-11** [comment]
grumble mumble merge conflicts.

**Comment by X0-11** [comment]
Nevermind then

**Pull request merged**
