### PR TITLE
Manually Controlled Turret Emplacements

### PR DESCRIPTION
**Pull request by X0-11**
MAJOR:
Adds a manual-control turret base.
Adds 2 subtypes of manual-control turrets.
Adds single use deploy kits for turret creation.
Addition of Insurrectionist Leader, with a single deploy kit as distinguishing item.

Minor:
Few small fixes to inhands and scopes missed in previous PR.

### CODE REVIEW

**Review by BDpuffy420 — CHANGES_REQUESTED** [review]
It seems the Insurrectionist Leader is Missing a HUD icon, error within  maps/insurrection/insurrection_hud_icons.dmi  by the looks of Travis  on lines  # 656-657

**Comment by BDpuffy420** [comment]
Might also want to update the change log too.

**Comment by bloxgate** [comment]
We should really get one of those bots that parses changelog entries after commits to the live branch.

**Review by BDpuffy420 — APPROVED** [review]

**Comment by X0-11** [comment]
Ready for review, Travis permitting.

**Comment by BDpuffy420** [comment]
Travis is happy, just awaiting for the others to comb through it.

**Comment by BDpuffy420** [comment]
Will Far Isle be included in this PR once the touch ups are done, or done separately?

**Comment by X0-11** [comment]
Separately. Far Isle could be merged much faster, it's a new map rather than some code.

**Review by bloxgate — COMMENTED** [review]
I'll take a more detailed look later, but a quick skim of the code doesn't show anything obvious.

**Comment by BDpuffy420** [comment]
You must update your change log file

**Comment by BDpuffy420** [comment]
update on review

**Comment by BDpuffy420** [comment]
LGTM

**Pull request merged**
