### PR TITLE
War crimes

### PR DESCRIPTION
**Pull request by caelaislinn**
- Fixes flamethrowers
- Fixes incendiary grenades

### CODE REVIEW

**Comment by frontline03** [comment]
How will we get one masterful cael

**Comment by caelaislinn** [comment]
Pray to whatever gods you believe in

Also they're both buildable already and I'll add them to innie black market vendors later

**Comment by PantasTheDank** [comment]
We still don't have access to phoron tanks

**Comment by frontline03** [comment]
Yes. We can't get any currently

**Comment by daPotato** [comment]
Believe the UNSC also loses access to phoron tanks in one of your other PRs.

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
