### PR TITLE
Huragok

### PR DESCRIPTION
**Pull request by BlackjackIsTired**
Added Huragok as functional borgs.

### CODE REVIEW

**Review by BlackjackIsTired — COMMENTED** [review]
Huragok.dmi

**Comment by BDpuffy420** [comment]
I think it would be better if they were based on the maintenance drone

**Comment by BlackjackIsTired** [comment]
> 
> 
> I think it would be better if they were based on the maintenance drone

They are, I just worded incorrectly, apologies.

**Comment by BDpuffy420** [comment]
Oh my bad!

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
