### PR TITLE
crs laser projector

### PR DESCRIPTION
**Pull request by Antonio7272**
:cl: Antonio72
rscadd: Added an actual laser projector to the CRS, now you can use it in ship combat.
rscadd: Modified slighly the bridge layout to compensate the removal of the old OB consoles.
/:cl:

New bridge layout

image

Laser Projector

image

The bridge didin't have anything important removed or added, its just for easier accesiblitily, if those changes are not wanted I will re-do the PR without them.

### CODE REVIEW

**Comment by Antonio7272** [comment]
tests failed because I forgot to remove a wire, fixing

**Comment by Antonio7272** [comment]
fixed the wires, the CRS should't run out of power and all the checks passed

**Comment by Stingray540** [comment]
Wasn't the laser projector (glassing beam) that you have re-added intentionally removed? I wasn't here when that change happened, so I can't really comment on it. If that was the case, what's changed?

**Comment by Antonio7272** [comment]
It's exactly the same one as the glassing ships, and if the UNSC DoO ever gets introduced to ship combat, we would need to make them equal as until I added it, we couldn't fire it on space combat

**Comment by Stingray540** [comment]
Exactly, that's an... "if". The UNSC DoO is not introduced to ship combat and adding this superweapon to the Covenant ship in a game mode that isn't primarily focused on ship combat is overkill. I wouldn't be surprised if the Covenant could easily overpower the fleet with this in space combat.

I agree that if we ever move back to ship combat as a focus the Covenant needs combat options back (torpedoes), but adding it now, in current rotation, does not seem like a good idea to me.

**Comment by Antonio7272** [comment]
I accidentaly put the fixed torpedoes code into this PR, any way to delete it, I want it to be its own not into this one

**Pull request closed without merging**
