### PR TITLE
Capture and Hold gamemode

### PR DESCRIPTION
**Pull request by X0-11**
A simple gamemode that focuses on capturing and holding areas of a new urban map
:cl: XO-11
rscadd: Adds a new city map for use in the Capture And Hold gamemode.
rscadd: adds a new gamemode, Capture And Hold.
tweak: Makes tanks 2x2 instead of 2x3.
/:cl:

### CODE REVIEW

**Review by BladeburstNINJA — COMMENTED** [review]
A suggestion for the smokeandillum commit: Instead of making only smoke and illum nades from the ubgl drop on click why not make all the grenades fired drop on click? Pasting this:
/obj/item/projectile/bullet/g40mm/launch(atom/target, var/target_zone, var/x_offset=0, var/y_offset=0, var/angle_offset=0)
    . = ..()
    kill_count = get_dist(loc,target)
instead of making it individually for each round would work (I've actually tested it and it works appropriately).

**Comment by BDpuffy420** [comment]
Is this good?

**Review by BDpuffy420 — APPROVED** [review]

**Review by bloxgate — APPROVED** [review]
It looks like this has been test merged on the box for a while, so if XO says its good we know it'll run at the very least.

**Comment by X0-11** [comment]
Yep it's been various fixes and such for a while now, the core mode has been finished for much longer. Good to merge.

**Pull request merged**
