### PR TITLE
Hostage maps and areas

### PR DESCRIPTION
**Pull request by TehSpoderman**
Added maps and areas for hostage

### CODE REVIEW

**Comment by BDpuffy420** [comment]
Travis is upset

**Comment by TehSpoderman** [comment]
WARNING: test "maps contain no step_[xy]" failed: 0 

No idea what this means exactly.

**Review by bloxgate — CHANGES_REQUESTED** [review]
You used the nudge command in a right click menu somewhere. You're going to have to open up the map file in Notepad++ or something and removing the offending bits.

~~Any chance we could get this PR'ed into its own branch too, or maybe just email it to me?~~
Yeah just go ahead and email it to me, I'll be sure to set the commit author and such right. It'll make making sure everything is bundled with the Hostage GM easier.

**Comment by BDpuffy420** [comment]
Since he is sending this to blox I'm going to close this

**Pull request closed without merging**
