### PR TITLE
Re-Implements Geminus City as a pickable mapset

### PR DESCRIPTION
**Pull request by X0-11**
:cl: XO-11
tweak: Geminus City has been compressed somewhat and re-implemented.
/:cl:
also makes geminus city the default mode rather than base assault

### CODE REVIEW

**Comment by bloxgate** [comment]
I'm a little concerned by all the spam about "Unknown Hazards" located on Z level "nothing" in the test log ([link](https://github.com/HaloSpaceStation/HaloSpaceStation13/runs/2740341124#step:6:60)). Any idea what that's about?

For what it's worth they don't seem new, though I don't recall seeing them before now. Geminus just has a lot of them.

**Comment by X0-11** [comment]
I think that's the unknown hazard objects being created. They're probably made and spawned in nullspace and then moved elsewhere. The amount of them is configurable on a per-mapfile basis iirc.

**Comment by bloxgate** [comment]
Ah, sounds good then. Guess I just never noticed them in the logs before.

**Review by bloxgate — APPROVED** [review]
Looks good for the most part. Any particular reason for keeping the old copies of the map in git? If we did ever want to go back we can always just revert this changeset, rather than keeping the old ones around.

Also, some map images may be useful. As a side-note, maybe we should look into getting mapdiffbot running on this repo.

**Comment by X0-11** [comment]
I was keeping the old maps around as an easy access reference to the older mapset if things are found missing from the new compressed one in playtesting.
I can provide mapimages if it's needed, shouldn't be too hard.

**Comment by bloxgate** [comment]
Map images would be nice, especially for the wiki. Not necessarily required for the PR to get merged.

**Pull request merged**
