### PR TITLE
A few minor fixes.

### PR DESCRIPTION
**Pull request by Nightspark43**
Fixes for game modes in the votes making it so only Secret, Extended and the current HaloStation modes can be voted for, as well as for languages, making it so humans can no longer select old Bay species, monkey, or Sangheili languages at will.

### CODE REVIEW

**Review by X0-11 — APPROVED** [review]
Looks good to me.

**Review by caelaislinn — APPROVED** [review]

**Review by bloxgate — APPROVED** [review]
LGTM.

Whoever merges, please remember to do a [ci-skip] commit to update the in game changelog too!

**Comment by BDpuffy420** [comment]
[ci-skip] ?

**Comment by X0-11** [comment]
Needs to be in the individual commit name, I think.

**Pull request merged**
