### PR TITLE
Adds the sparowhawk to the dme.

### PR DESCRIPTION
**Pull request by Kmc2000**
Adds my sparowhawk icon to the DME, will need filing etc.

Use this cael.

### CODE REVIEW

**Comment by Kmc2000** [comment]
Don't merge yet, goofed

**Comment by Kmc2000** [comment]
DME fixed, now it just adds what it should

**Comment by Kmc2000** [comment]
Snuck in some special snowflake armour, all animated of course

**Comment by BDpuffy420** [comment]
cool

**Comment by caelaislinn** [comment]
icons arent tracked in the DME... just chuck the files into the right folder then commit+add them like this

**Pull request merged**
