### PR TITLE
Asteroid mining fix

### PR DESCRIPTION
**Pull request by Flaksim**
- Fixes incorrect space tiles on mining asteroid.

### CODE REVIEW

**Comment by caelaislinn** [comment]
The docking umbilicals commit is missing?

**Comment by bloxgate** [comment]
No, it's there. It just flips the directions, as indicated in the commit description. Would've been a bit more helpful to have that in the first line, but it does what it says.

**Comment by caelaislinn** [comment]
Oh both commits were for map changes. Got pretty confused there

**Review by DoctorOctopusTheOctopi — APPROVED** [review]
Claims to be a small patch, looks good .dmm wise nothing alarming. 387 additions 388 deletions. Overall nice bugfixerino! 👍 🐙

**Comment by DoctorOctopusTheOctopi** [comment]
Merger should squash and merge since there are two commits here, just to keep our history clean.

**Pull request merged**
