### PR TITLE
Geminus city expansion+Map fixes.

### PR DESCRIPTION
**Pull request by Flaksim**
*Expands Geminus to 3 Z levels.
*Adds an aditional level to exoresearch, for Orion Project research.
*Adds comms equipment to innie base, geminus city.
*Minor Fixes to UNSC Prowler and UNSC Frigate.

### CODE REVIEW

**Review by BDpuffy420 — APPROVED** [review]

**Comment by Flaksim** [comment]
Travis failing on the frigate map test is completely normal and shouldnt stop this from being merged: its failing because the elevator areas are coded in but not used yet. This is the intent right now as they will be added in mapwise at a later stage (its a serious headace getting them to work correctly)

**Comment by Flaksim** [comment]
Geminus check will fail because there are no map images, which isnt necessary either way. That specific travis error should be ignored.

**Review by DoctorOctopusTheOctopi — CHANGES_REQUESTED** [review]
Please rectify these two errors.. Errors have been enlarged.

UNIT_TEST ##: [MAP: Disposal segments shall connect with other disposal pipes]: Following disposal pipe does not connect correctly: The disposal pipe (/obj/structure/disposalpipe/segment) ([0x20043ea]) (the rock) (76,132,2) (/turf/simulated/mineral/random/high_chance)

UNIT_TEST ##: [MAP: Disposal segments shall connect with other disposal pipes]: Following disposal pipe does not connect correctly: The disposal pipe (/obj/structure/disposalpipe/segment) ([0x20043eb]) (the raw carbon deposit) (77,132,2) (/turf/simulated/mineral/random/high_chance)

UNIT_TEST ##: [MAP: Disposal segments shall connect with other disposal pipes]: Following disposal pipe does not connect correctly: The disposal pipe (/obj/structure/disposalpipe/segment) ([0x20043ec]) (the rock) (78,132,2) (/turf/simulated/mineral/random/high_chance)

UNIT_TEST ##: [MAP: Disposal segments shall connect with other disposal pipes]: Following disposal pipe does not connect correctly: The disposal pipe (/obj/structure/disposalpipe/segment) ([0x20043ed]) (the rock) (79,132,2) (/turf/simulated/mineral/random/high_chance)

UNIT_TEST ##: [AREA: Areas shall be coherent]: The Mine (/area/planets/Geminus/indoor/mining) ([0x400001e]) (172,97,1) is incoherent. Expected 1 subarea, fill gave 2.

## UNIT_TEST ##: !!! FAILURE !!! [MAP: Disposal segments shall connect with other disposal pipes]: 4 disposal segments did not connect with other disposal pipes.

## UNIT_TEST ##: !!! FAILURE !!! [AREA: Areas shall be coherent]: Found 1 incoherent area.

**Review by caelaislinn — CHANGES_REQUESTED** [review]
/area/planets/Geminus/indoor/mining is split up as well into two disconnected chunks somewhere, that should be 1 continuous area

**Comment by Flaksim** [comment]
Requested changes have been made.

**Comment by caelaislinn** [comment]
/area/planets/Geminus/indoor/mining but there are still a bunch of disconnected disposal pipes

**Comment by Flaksim** [comment]
Odd, i removed those... I’ll take another look tonight.

**Comment by Flaksim** [comment]
Only part failing now is the map images, for obvious reasons, travis wise this can pass.

**Review by caelaislinn — APPROVED** [review]

**Pull request merged**
