### PR TITLE
Riley Kitten Donor Arrives

### PR DESCRIPTION
**Pull request by Kozi32**
:cl: Kozi32
rscadd: add Riley donor armor
/:cl:

Mind inspect the donor code about riley part.

### CODE REVIEW

**Comment by BDpuffy420** [comment]
“618code/modules/halo/clothing/doneritems.dm:1210:error: up: expected end of statement“. Did you even compile before PR’ing this ?

**Review by bloxgate — CHANGES_REQUESTED** [review]
You can't have `"` by itself inside strings. You need to escape it like this:

```dm
"this is a string that contains a \""
```

**Comment by bloxgate** [comment]
You also should make the first :CL: in your changelog lower case so it shows as :cl:

**Review by caelaislinn — CHANGES_REQUESTED** [review]
No more meme donator items.

**Comment by BDpuffy420** [comment]
DFE126E3-480A-4913-9F2D-F6A25A7DDCB9

**Comment by CdrRiley** [comment]
request changes aint need anymore?

**Pull request merged**
