### PR TITLE
Fixes Insurrection bomb-detonation warning activating early

### PR DESCRIPTION
**Pull request by X0-11**
Title
This is also intefering with the auto-end-when-dead system

### CODE REVIEW

**Comment by X0-11** [comment]
Travis issue is due to stranded timeout.

**Comment by caelaislinn** [comment]
Wong button

**Comment by BDpuffy420** [comment]
would the timeout cause issues with the GM

**Comment by X0-11** [comment]
No, Its just a timeout due to the area coherency check.

**Comment by BDpuffy420** [comment]
Ah nice.

**Pull request merged**
