### PR TITLE
Weapon & Clothing Vendor Categories, Armor Sets, and other QoL changes

### PR DESCRIPTION
**Pull request by loafe**
:cl: Loafe
rscadd: Adds weapon & clothing vendor categories
rscadd: Adds armor sets for UNSC and EVA Covenant
rscadd: added extended oxygen tanks for EVA armor sets on both sides
rscadd: tweaked number of normal armor sets available to marines & odsts

/:cl:

### CODE REVIEW

**Comment by caelaislinn** [comment]
There are several different travis failures here. However XO's changes need to be integrated first before the other ones can be addressed

**Comment by loafe** [comment]
Alright, I added XO's changes, shouldn't be any conflicts anymore

**Comment by caelaislinn** [comment]
The Travis failure is because the code runtiming, but there is a problem with the Byond installation. I'm going to need some help and research to figure this one out

**Comment by caelaislinn** [comment]
This is now Travis passing. I suggest you'll need to find another way to add categories to vendors

**Comment by loafe** [comment]
I will try a few techniques, some will take significantly longer than others. The armor sets are still functional, if you want to merge those and I will get the categories figured out later.

**Comment by loafe** [comment]
I added Categories again using a `"Category" = -1,` line, hopefully it keeps DM from spawning runtime errors

**Review by X0-11 — APPROVED** [review]
looks like it's passing travis now

**Pull request merged**
