### PR TITLE
Urf Ship Crew Random Spawns and Misc Items for flavor

### PR DESCRIPTION
**Pull request by lngredients**
- tweak: "Added in random clothes sets on Innie ship. Some random materials as well."
  - tweak: "Random weapon and ammo spawns were added in as well to the innie ship."
  - tweak: "A few static goodies were spread around the ship as well.

### CODE REVIEW

**Comment by Desolane** [comment]
Remove the heavy sniper from the random spawns.

**Comment by lngredients** [comment]
Alrighty, will do.

**Comment by caelaislinn** [comment]
NPC weapon traders have a chance to spawn with heavy snipers, LMGs and rocket launchers for exorbitant amounts of money. They should be possible to get through a lot of hard work and not just lying around

**Comment by lngredients** [comment]
This URF update should be good to go. Let me know if I went overboard with the Colossus Armor.

**Comment by Flaksim** [comment]
1: what is and where is that colossus and zeal stuff?
2: stats look OP man, needs a nerf somewhere.

**Comment by lngredients** [comment]
It's placed in the Innie base on level 4. I made it so strong because when you wear it you move pretty slowly, meaning you are likely to be shot a lot more then your average person while using it.

**Comment by lngredients** [comment]
If I could get the deflection code working I wouldn't mind lower the armor thickness and values though.

**Comment by lngredients** [comment]
Even more, that is.

**Comment by lngredients** [comment]
Let me know if this is good to go.

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
