### PR TITLE
Adds Phantoms

### PR DESCRIPTION
**Pull request by OuterMostMonk**
:cl: OuterMostMonk
rscadd: Added Phantom dropships
rscdel: Replaced spirits on the Covenant cruiser with phantoms
rscadd: Spawnpoints for Zealot and Chieftain
/:cl:

The Covenant have upgraded their dropships to Phantoms, they are smaller than a Spirit but just as powerful. (Equivalent to UNSC Pelicans)

### CODE REVIEW

**Comment by X0-11** [comment]
Some maps are failing checks.

**Comment by OuterMostMonk** [comment]
Strange, it should work. Though one issue that may be the cause is for some reason the phantom_dropship file is not included by default which causes maps to fail since they cannot load the vehicle properly.

**Comment by X0-11** [comment]
I see no reason why you can't include the phantom dropship file in the load order by default.

**Comment by OuterMostMonk** [comment]
Okay didn't realise that I just needed to update the dme file. Hopefully it is good now

**Comment by OuterMostMonk** [comment]
Foiled by the accursed stairs once again

**Comment by Aroliacue** [comment]
Re-running it for ya

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
