### PR TITLE
Covenant IDs & Pod Resprite

### PR DESCRIPTION
**Pull request by ghost**
Adds covenant ID sprites for each race and rank
Resprites covenant pods so they are no longer **hot** pink

### CODE REVIEW

**Comment by X0-11** [comment]
covenant pod resprite is in the wrong file. Correct file is code/modules/halo/vehicles/covenant_pods.dmi

**Review by caelaislinn — APPROVED** [review]

**Review by caelaislinn — DISMISSED** [review]
Move those pod sprites to the right file

**Comment by caelaislinn** [comment]
You need to resolve the conflict in the dmi. Manually doing it is probably easiest. Do you know how?

**Comment by ghost** [comment]
> You need to resolve the conflict in the dmi. Manually doing it is probably easiest. Do you know how?

I don't, actually. The last time I had conflicts I just fiddled around until it seemed fixed. And even then, it took a second PR to get the covenant slipspace core in properly.

**Comment by ghost** [comment]
I did the do.

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
