### PR TITLE
Stranded and Firefight gamemodes

### PR DESCRIPTION
**Pull request by caelaislinn**
Overhauls Stranded to fix a number of longstanding issues, and adds the new Firefight gamemode (UNSC defend against waves of Covenant simple mobs) and maps. Also includes various fixes and improvements to gamemodes and simple mob AI. Main changes include: 

- Renames Stranded to a new "Firefight" gamemode type, and makes Stranded (player UNSC vs simple mob Flood) a subtype of Firefight (player UNSC vs simple mob Covenant)
- Adds Crusade subtype (player Covenant vs simple mob UNSC)
- Firefight now has the capability to pull enemy mobs from any faction list
- Firefight waves now have a limited spawn amount, and the rest period only starts when all enemies are defeated (default 4 waves, with evac ship arriving at the start of the last wave). 
- Enemy mobs in Firefight will now follow players to anywhere on the map
- UNSC Achlys as well as the firefight gamemode subtypes now have a forced gamemode, so no other gamemodes are votable
- Simple mob assault_target pathing is working again, and their AI should be somewhat smarter than before
- Fixes some issues with overmind, although there are likely other outstanding issues 
- Adds "destructible" structure type which fixes and standardises several defensive structures (steel/plasteel/marine barricade, sandbag, tanktrap). 
- Adds coloured night vision overlay effect and standardises all night vision to 5 tile range
- Misc other bugfixes and tweaks, including some Covenant job tweaks

🆑 CaelAislinn
bugfix: Fixes many outstanding issues with Stranded/Desert Outpost, it should play much more nicely now. 
experimental: Adds Firefight gamemode where UNSC players defend against waves of Covenant NPCs
bugfix: Fixes a lot of issues with defensive structures including directional blocking. Metal and plasteel barricades should be buildable now
/🆑

### CODE REVIEW

**Comment by caelaislinn** [comment]
Partially address #2259 fixes #1659

**Comment by caelaislinn** [comment]
Waiting on #2386 to be merged for the faction changes, mainly defender mob stuff, that I need to finish off firefight

**Comment by caelaislinn** [comment]
Ready to merge

**Comment by caelaislinn** [comment]
#2122

**Review by X0-11 — APPROVED** [review]

**Pull request merged**
