### PR TITLE
Adds jobs for medical ship (Deliverance) 

### PR DESCRIPTION
**Pull request by erty80s**
-Adds job datums for medical ship crew and captain
-Adds landmarks for those respective jobs

### CODE REVIEW

**Comment by erty80s** [comment]
The landmarks arent on the deliverance yet, a mapper might have to do that

**Review by caelaislinn — CHANGES_REQUESTED** [review]
There is a lot of unrelated changes in here. Take out all the changes to the Covenant stuff or document them in your PR and changelog

**Comment by erty80s** [comment]
I didnt any covie stuff but ill see why the dmi conflicts and also delete all the other useless commits

**Comment by caelaislinn** [comment]
It also looks like you reverted the changes you made to the Deliverance jobs.

**Comment by erty80s** [comment]
I delete my own files and replaced them with new ones so they wouldnt conflict on my own fork. Thankfully the issue is something else

**Comment by caelaislinn** [comment]
Do a soft revert at an unrelated commit a week ago (to keep your changes), then hard revert the changed files that aren't yours, then commit your changes, then update your branch.

**Comment by erty80s** [comment]
Alright will do after a good night's rest, thanks.

**Pull request closed without merging**
