### PR TITLE
Various changes and fixes

### LINKED ISSUE #2570: Adrenaline OD With New OD System
#### Description of issue

When you get shot a few times, you OD on adrenaline, which makes you get stunned and throw up, stunning you for 10 seconds or so. Since the OD limit of Adrenaline is 10, this happens very easily, and almost guarantees that you die.

#### Difference between expected and actual behavior

Before, adrenaline OD just did heart damage and gave you the shakes, where now it makes you keel over and throw up, after which you are stunned. You should just get the shakes and heart damage.

#### Length of time in which bug has been known to occur

Since the Chem OD rebalance

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

### LINKED ISSUE #2577: AI access node routing being very finnicky and bugging out with freshly hacked nodes that are apart of a different system than the ship/station the AI initially spawned in.
#### Description of issue 
I was covvie AI and got slotted into the ODP. I hacked multiple nodes to access 4, but repeatedly i'd get a 'you need level 3 access' when trying to interface with doors. Now, i could easily air siphon, bolt and electrify doors ALA level 4 access. But the level 3 things would sometimes work on one level 4 node, then not work on another level 4 node.

#### Difference between expected and actual behavior
I should have access to the whole slew of level 1, 2, 3 and 4 abilities from nodes. Instead it gives me a very finnicky smattering of level 1, 2 and 4 abilities.

#### Steps to reproduce 
Slot an AI into a fresh access node terminal in an area it has no node access. Start hacking nodes and try and use the full slew of level 1-4 access and watch it bork out with trying to open or close doors/disable safeties/overide timing.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

### PR DESCRIPTION
**Pull request by X0-11**
:cl: XO-11
tweak: ONI has tweaked your adrenaline production. It's now less toxic. Yes, ONI. Even for the covenant species.
tweak: resets brute pain, brute, burn modifiers to provide a clean balance slate to work off.
tweak: spirit should now be able to fire
tweak: plasma rifle has been equpped with better heat dispersion tech
tweak: kig-yar shield slow down change
/:cl:
closes #2570 
closes #2577

### CODE REVIEW

**Comment by bloxgate** [comment]
Personally I'd prefer a revert of #2562, rather than having to snowflake less lethal overdoses for everything. 

If people are abusing the lack of a strong OD on painkillers (which I presume is the initial problem) there are plenty of ways to make that more disruptive without affecting every other chem.

**Comment by X0-11** [comment]
The problem lies in abusing the OD of any chemical. This is the only chemical that I think will even need a snowflake override specifically because this chemical is only capable of being generated when taking damage and thus players cannot stop it from being created. The rest are voluntary.

**Comment by bloxgate** [comment]
Given that this is pretty game breaking, I'm not going to be opposed to merging this for the time being, but I do think that there are better ways of handling the problem than making every overdose automatically deadly.

For instance we could remove biofoam's ability to significantly heal internal organ damage. I'm not a fan of biofoam being as big of a fixall as it is - it significantly hinders people's knowledge of actual medical for when there's something that biofoam can't handle. Additionally we already issue peridaxon autoinjectors in the field medical kits which could help with legitimate cases of organ failure. If the medics waste it on someone who took 600U of tramadol, that's on them.

**Review by bloxgate — APPROVED** [review]
Perfectly fine codewise, though I still have reservations about the overall changes we've done to OD.

**Comment by X0-11** [comment]
It's been made pretty clear that people don't want to have significant medical knowledge to play here.

**Comment by bloxgate** [comment]
Biofoam is not and should not be a fixall. The fact that it is so close is the reason this OD problem exists in the first place.

I would also argue that the buff we've made to OD actually makes involved medical knowledge more necessary as well. There is no non-surgical way to repair fully destroyed organs as far as I'm aware - and a large overdose is liable to do enough liver damage to cause the organ to fail. Rather than trying to rework biofoam to encourage the use of less powerful, but already present methods (peridaxon autoinjectors are readily available and specifically named in a way to indicate its purpose for treating organ damage) we've simply changed the game to immediately punish overdoses with death. Even if the immediate toxin damage doesn't kill you the lack of detailed medical knowledge when you inevitably kill an organ from the accumulated toxin damage will.

This specific conversation may benefit a bit more from being moved into its own issue.

Edit: Specifically I'd like to point out that biofoam does not repair dead organs, as it doesn't seem to undo the effects of the die() proc [here](https://github.com/HaloSpaceStation/HaloSpaceStation13/blob/alpha/code/modules/organs/internal/_internal.dm#L56) which is in turn called [here](https://github.com/HaloSpaceStation/HaloSpaceStation13/blob/alpha/code/modules/organs/organ.dm#L131) or when an infection reaches end stage.

**Review by caelaislinn — DISMISSED** [review]
Undocumented changes including significant jiralhanae nerfs

**Comment by X0-11** [comment]
changelog updated

**Comment by Tupinambis** [comment]
don't name your PR less adrenaline OD when there are other bits in it. I'm not a modularity freak, but you should probably just name it something else.

**Comment by X0-11** [comment]
This is what happens when prs linger

**Comment by bloxgate** [comment]
You can have multiple branches and multiple PRs open at the same time.

**Comment by X0-11** [comment]
Fully aware, I just turn small prs like this into various-fix esque prs

**Pull request merged**
