### PR TITLE
Glove bugfix

### PR DESCRIPTION
**Pull request by CapCamIII**
Innie gloves were meant to be identical to UNSC ones, and UNSC gloves had a comment specifically saying they should be insulated, so I added that to both.
SOE gloves also had the same problem as the other two with intended insulation, but not having it.

Sidenote: Why is insulation called siemens_coefficient in code, thats really confusing! :(

:cl: CaptainCamo
tweak: All combat and standard gloves have a base insulation value of .15, compared to .50 of most gloves, specific values detailed below.
tweak: ODST 0-.1, marine .5-.15, SOE .5-1.5, innie .5-1.5, grunt .5-1.5, drone 0-.05, spartan 0-.05, sanghelli 0-.15, tvoan 0-.15.
bugfix: Fixes paths on some donor gear SOE gloves, giving them proper stats sprites.
maptweak: Insurrectionist Ship Captain quarters can be accessed by Innie officers now.
maptweak: Insurrectionist cargo shuttle door can be accessed by every insurrectionist now.
maptweak: Insurrectionist medbay now has a body scanner and prosthetic printer
maptweak: URF Liberator umbis are one way now.
rscadd: SOE gloves are now insulated and heat proofed, that means they dont get shocked by doors and can take light tubes from walls now
tweak: Innie mission shuttle APC has a larger power cell now
tweak: Orion defectors, SOE officers, and SOE captains can access innie cargo now
tweak: SOE get custom loadout items and bank accounts now
bugfix: Innie slipspace drive can be used by innies now.
tweak: The following roles now have access to supply drops Tvoan champion, Sanghelli Zealot, Sanghelli Honor Guard, Sanghelli Spec Ops, Minor Prophet, SOE Commando Officer, SOE Commando Leader.
tweak: The following roles, as well as any with proper supply drops, have access to personal supply drops Tvoan commando, Tvoan murmillo, Sanghelli Major, Sanghelli Minor, Unggoy Spec Ops, Unggoy Ultra, Unggoy Heavy, Brute Major, Brute Minor, Yanmee Ultra, UNSC Specialist, UNSC Hellbringer, SOE Commando
tweak: Tvoan commando now only has personal supply drops.
/:cl:

### CODE REVIEW

**Comment by X0-11** [comment]
It's more likely that the comment on those gloves was outdated and not changed when the gloves were modified. What's the reasoning behind having them fully block electric shocks?

**Comment by CapCamIII** [comment]
Oh, it was outdated?
Shocks do kind of absurd damage, and can cause a big stun depending on rng.
When I was testing, I managed to hand-gib myself even with gloves on, in just 2-4 shocks,

**Comment by X0-11** [comment]
That's likely down to the comical amount of power coursing through most of our electrical networks. The damage scales. My biggest issue with this is how this is going to hit Covvies. After all, they don't tend to have gloves and this'll allow the unsc to set electrified doors with impunity.

**Comment by CapCamIII** [comment]
every cov role does have a glove, I think, I can add insuls to them as well.

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
