### PR TITLE
Adds spicy extended as a gamemode

### PR DESCRIPTION
**Pull request by X0-11**
A curated set of antags with modifications to generalise their limitations out so they work on the server.
Traitors have kill/maim only, and anyone can be their target.
Revs instead have 3-5 people they must recruit/capture/kill.
Changelings have standard genome absorb and kill objectives.
Revs and traitors, when they are assigned a kill objective, provide the target with a warning to allow them to prepare for an attack.
:cl: XO-11
tweak: A new mode is available on a few maps, Spicy Extended
tweak: New mode places all factions in friendly relations to eachother and instead uses base game antags to cause conflict.
tweak: Traitor, Flood Infiltrator Changeling and Revolutionaries are available.
tweak: Spartan laser tweaks.
tweak: Colonist tweak
tweak: Fixed Geminus  tunnel to space map issue
/:cl:

### CODE REVIEW

**Comment by BDpuffy420** [comment]
I really don't approve of this water down versions of base ss13 modes doesnt really fit what we are going for, rev and traitor sure but the  Flood Infiltrator (Changeling) is not it, maybe for admeme event but not full on mode players can vote on, and you have  other fixes bundled in this PR as well now too/

**Comment by X0-11** [comment]
It's a simple voteable alternative mode that players seem to like.  You can obstruct this if you don't like it on principle, but that's your choice and I'll make mine.

**Comment by BDpuffy420** [comment]
And SOME players like slayer and it kills pop

**Comment by X0-11** [comment]
It keeps a number of players consistently engaged; is dynamic; and allows the two main factions to play together, as well as implementing some of that old urf vibes when a colonist or other lower power role is selected as rev/traitor/ling. It's just a simple mode. If people don't like it, they'll just not vote it in.

**Comment by BDpuffy420** [comment]
I like to have variety which is nice, but when ya turn down other gamemode ideas that have  alittle more broad appeal than this its is kinda silly to be honest. I think we should  focus on more better stuff than rehashing decade old modes

**Comment by X0-11** [comment]
This is way easier to implement than a number of other suggested modes. That's the main divider.

**Comment by BDpuffy420** [comment]
> It keeps a number of players consistently engaged; is dynamic; and allows the two main factions to play together, as well as implementing some of that old urf vibes when a colonist or other lower power role is selected as rev/traitor/ling. It's just a simple mode. If people don't like it, they'll just not vote it in.

I think the isssue with that we have people who will troll vote stuff people dont want if staff isnt on and kill pop which has happen alot with slayer. The "they just wont vote for it" really wont hold up

**Comment by X0-11** [comment]
Sounds like staff should track down these "troll voters" and figure out why they're doin what they do.

**Comment by BDpuffy420** [comment]
yeah's that fine and dandy it just still get the point across "SOME" and I mean SOOOOOME people like a mode doesnt really justify having it in rotation, Like some people liked packwar and OP:red why not re add them since this is based of SOME people liking it

**Comment by BDpuffy420** [comment]
If OP:Red gets added back a new map is in order tho

**Comment by X0-11** [comment]
They weren't removed because they were disliked, they were removed because they were fundamentally broken. Packwar failed to function and caused mega lag due to the way the map was build, and OP;RF was, well OP;RF.

**Review by BDpuffy420 — APPROVED** [review]

**Pull request merged**
