### PR TITLE
Recolored Brute Armors

### PR DESCRIPTION
**Pull request by Max-023**
:cl: Guprei
tweak: All brute armors, softsuits, and the undersuit sprites
tweak: Updated tcomms backpack sprite for the UNSC
/:cl:

### CODE REVIEW

**Comment by caelaislinn** [comment]
#2386 moves the changed covenant sprites, I'll get you to hold off and reapply the new sprites after it get's merged

**Comment by Max-023** [comment]
Alright, PR updated.

**Comment by caelaislinn** [comment]
Can you list the sprites that were updated? A lot of the brute gear is broken at the moment and I was planning to go through and fix them

**Comment by Max-023** [comment]
Brute minor armor, brute major armor, brute captain armor, brute undersuit (cov), brute minor and major soft suits, and the iconstates for all.

**Review by caelaislinn — APPROVED** [review]

**Comment by caelaislinn** [comment]
These look great. I would have merged them straightaway but I'm chasing the issues with Brute gear sprites and don't want to conflict. 

Also the new undersuit sprite looks very similar to the softsuit [spacesuit] sprite. I love it but I don't think it works as an undersuit. It looks too high tech. Here are some images for comparison. 
d2d2339ac9e5599b8e29951151aba975

Also, while you are touching this file, can you remove the duplicate spiker inhand sprites?

**Comment by Max-023** [comment]
I can remove the spiker inhands, sure.

As for the brute undersuit, I just made it purple like in H3. Not sure how it looks high tech.

**Pull request merged**
