### PR TITLE
Mechs in cargo

### PR DESCRIPTION
**Pull request by X0-11**
:cl: XO-11
rscadd: The UNSC and Covenant now have access to the Goblin and HRUNTING mechs in their supplies.
tweak: You can no longer directly input money into supply consoles.
tweak: To mitigate this, the URF now gain money over time and their missions now reward more money and favour.
/:cl:

### CODE REVIEW

**Review by Aroliacue — APPROVED** [review]
Seems good, I bet people will still try to export money via the shuttle lmao

**Comment by Tonklaatech** [comment]
Can you add some sort of low tier grade for the urf as a response to faction mech? Like maybe a upgrade kit for their orions turning them into full spartans

**Comment by BDpuffy420** [comment]
> Can you add some sort of low tier grade for the urf as a response to faction mech? Like maybe a upgrade kit for their orions turning them into full orions

The idea was re-add the X-52 onto the URF ship and let them build the old Mark I

**Comment by X0-11** [comment]
URF will have a variant added later.. At the very least, they'll get a resprited HRUNTING.

**Pull request merged**
