### PR TITLE
Donator Armor, Helmet, and Weapon Fixes

### PR DESCRIPTION
**Pull request by Ashvor**
Adds the Flashlight verb to the MA5B Assault Rifle and related weapons. Fixing the lack of a flashlight on the weapon. Additionally, a in hand sprite has been added to the M6S SOCOM so it is no longer invisible on the character when wielding.

Fixed Karmac's Donator Armor, which was not working properly. Added the additional code for the UNSC CH252 Helmet and EVA Helmet to have flashlight option. As it was requested in Embassy. Waiting final approval with the rest of these items in this PR.

### CODE REVIEW

**Comment by X0-11** [comment]
flashlight verb was removed pending addition as an attachment. if you want the flashlight, please make the attachment.

If you're adding lights to the 'rine helms, add 'em to covvie helms too

**Comment by Ashvor** [comment]
Hot fixed the PR, so it is just the Karmac's Donator Armor fix and M6S SOCOM sprite in hand fix. Rest should be restored to what it was. Not going to bother with the flashlight coding.

**Comment by X0-11** [comment]
Did you also remove the helmlight changes, 'cause I can't see them

**Comment by Ashvor** [comment]
Correct I did. All flashlight code, not going to mess with it. Just fixing the other two issues and that is it.

**Comment by X0-11** [comment]
as far as I could tell the helm light code was fine but atomisation by moving that to another PR would be a good move

**Comment by Ashvor** [comment]
Fixed, should be ready to merge.

**Review by X0-11 — APPROVED** [review]

**Pull request merged**
