### PR TITLE
Removes Vagina From Covvie Pods

### PR DESCRIPTION
**Pull request by ghost**
I don't know how it got there either, but it's gone now

### CODE REVIEW

**Comment by BDpuffy420** [comment]
Uhhhh nani the fuck?

**Comment by GeneriedJenelle** [comment]
Not even a screenshot my dude? kmt

**Comment by ghost** [comment]
It was pointed out to me so I fixed it.
@Generied you can just open the changed file to see it.

**Review by BDpuffy420 — APPROVED** [review]

**Comment by caelaislinn** [comment]
You have a duplicate commit and 2 unrelated commits which are empty. This is good to merge but maybe be a bit more careful about your commit history and branching next time

**Pull request merged**
