### PR TITLE
Nerfs brain damage, geminus fixes, overmap weapon tweaks, HA sprite fix

### PR DESCRIPTION
**Pull request by caelaislinn**
See commit log. I'm not happy with how strong biofoam is so I probably want to nerf it. Reducing the impact of brain damage means biofoam doesnt have to be so strong

### CODE REVIEW

**Comment by X0-11** [comment]
Biofoam's ability to heal brain damage is a side-effect of the organ healing ability. Biofoam could just be changed to filter out brain-type organs so it doesn't heal those.

**Comment by caelaislinn** [comment]
Yeah I agree, but I think having a blanket healing effect on all other organs is still too much. It should also be ineffective or toxic to inject it imo.

**Comment by X0-11** [comment]
It's not a true heal, it only (at most) returns the organs to their bruised state.

**Comment by caelaislinn** [comment]
Which means the negative side effects of those organs are no longer applied and the character is back to full fighting effectiveness.

**Review by X0-11 — APPROVED** [review]

**Review by bloxgate — CHANGES_REQUESTED** [review]
We'll need to do a sweep of the code and make sure that everything that causes brain damage uses the proc and not just an addition. I'm sure there's some code that does that somewhere, for whatever reason.

I'm also concerned about changing something so intricately connected to how death works in Baymed, along with nerfing away yet another part of medical. I personally agree more with the suggestion to add some sort of organ filters to biofoam - after all having a mass expand in your brain to close things up probably isn't actually good for you. After that - if the medics don't bring alkysine that's on them.

**Comment by caelaislinn** [comment]
Yeah you're right blox... I forgot about immortality unless asphyxiated. Personally I'm not such a fan of realistic medical any more after playing more Colonial Marines. Gotta fix these conflicts before merge anyway

**Comment by X0-11** [comment]
The unfun nature of super realistic medical is why biofoam is as powerful as it is. It essentially treats all the annoying stuff, whilst still allowing the unprepared to be affected by it.

**Review by BDpuffy420 — DISMISSED** [review]
Please fix file conflicts

**Comment by caelaislinn** [comment]
@bloxgate my changes to take_damage() are an override not a new proc, so it should already be used wherever brain damage is applied. My rationale for nerfing this is that it interferes with gameplay to an unreasonable extent after being exposed to vacuum but surviving. Given emergency oxy tanks literally last about 60 seconds right now and you are presumably still taking pressure damage during that time, even "prepared" players will experience a significant (but fair) risk of death. 

Just being unable to breath for 30-60 seconds can apply large amounts of permanent (healable) brain damage however. And high brain damage is extremely punishing as it will randomly black you out and make you drop what you are holding.

**Comment by caelaislinn** [comment]
I'm an idiot this should be in 3 PRs

**Review by BDpuffy420 — APPROVED** [review]

**Review by bloxgate — APPROVED** [review]
As long as we're sure this doesn't make people immortal I'm fine with it for now.

I still do disagree with nerfing medical, especially when there are already ways to deal with brain damage (like alkysyne).

**Pull request merged**
